/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProjecaoRouteImport } from './routes/_authenticated/projecao'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCobrancasRouteImport } from './routes/_authenticated/cobrancas'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedMasterRouteRouteImport } from './routes/_authenticated/master/route'
import { Route as AuthenticatedContadorRouteRouteImport } from './routes/_authenticated/contador/route'
import { Route as AuthenticatedCentrosDeCustoRouteRouteImport } from './routes/_authenticated/centros-de-custo/route'
import { Route as AuthenticatedMasterIndexRouteImport } from './routes/_authenticated/master/index'
import { Route as AuthenticatedConfiguracoesIndexRouteImport } from './routes/_authenticated/configuracoes/index'
import { Route as AuthenticatedCentrosDeCustoIndexRouteImport } from './routes/_authenticated/centros-de-custo/index'
import { Route as AuthenticatedVendasProdutosRouteImport } from './routes/_authenticated/vendas/produtos'
import { Route as AuthenticatedVendasPedidosRouteImport } from './routes/_authenticated/vendas/pedidos'
import { Route as AuthenticatedVendasClientesRouteImport } from './routes/_authenticated/vendas/clientes'
import { Route as AuthenticatedMasterConvitesRouteImport } from './routes/_authenticated/master/convites'
import { Route as AuthenticatedFinanceiroTransacoesRouteImport } from './routes/_authenticated/financeiro/transacoes'
import { Route as AuthenticatedFinanceiroRegrasNomesRouteImport } from './routes/_authenticated/financeiro/regras-nomes'
import { Route as AuthenticatedFinanceiroImportarNfeRouteImport } from './routes/_authenticated/financeiro/importar-nfe'
import { Route as AuthenticatedFinanceiroImportarRouteImport } from './routes/_authenticated/financeiro/importar'
import { Route as AuthenticatedFinanceiroFluxoCaixaRouteImport } from './routes/_authenticated/financeiro/fluxo-caixa'
import { Route as AuthenticatedFinanceiroContasReceberRouteImport } from './routes/_authenticated/financeiro/contas-receber'
import { Route as AuthenticatedFinanceiroContasPagarRouteImport } from './routes/_authenticated/financeiro/contas-pagar'
import { Route as AuthenticatedFinanceiroContasBancariasRouteImport } from './routes/_authenticated/financeiro/contas-bancarias'
import { Route as AuthenticatedFinanceiroConciliacaoRouteImport } from './routes/_authenticated/financeiro/conciliacao'
import { Route as AuthenticatedFinanceiroCategoriasRouteImport } from './routes/_authenticated/financeiro/categorias'
import { Route as AuthenticatedFinanceiroCartoesRouteImport } from './routes/_authenticated/financeiro/cartoes'
import { Route as AuthenticatedFinanceiroCalendarioRouteImport } from './routes/_authenticated/financeiro/calendario'
import { Route as AuthenticatedContadorRelatoriosRouteImport } from './routes/_authenticated/contador/relatorios'
import { Route as AuthenticatedContadorLancamentosRouteImport } from './routes/_authenticated/contador/lancamentos'
import { Route as AuthenticatedContadorExportarRouteImport } from './routes/_authenticated/contador/exportar'
import { Route as AuthenticatedContadorDashboardRouteImport } from './routes/_authenticated/contador/dashboard'
import { Route as AuthenticatedConfiguracoesUsuariosRouteImport } from './routes/_authenticated/configuracoes/usuarios'
import { Route as AuthenticatedConfiguracoesPermissoesRouteImport } from './routes/_authenticated/configuracoes/permissoes'
import { Route as AuthenticatedConfiguracoesPerfilRouteImport } from './routes/_authenticated/configuracoes/perfil'
import { Route as AuthenticatedConfiguracoesOpenBankingRouteImport } from './routes/_authenticated/configuracoes/open-banking'
import { Route as AuthenticatedConfiguracoesNotificacoesRouteImport } from './routes/_authenticated/configuracoes/notificacoes'
import { Route as AuthenticatedConfiguracoesCobrancasRouteImport } from './routes/_authenticated/configuracoes/cobrancas'
import { Route as AuthenticatedConfiguracoesAprovacoesRouteImport } from './routes/_authenticated/configuracoes/aprovacoes'
import { Route as AuthenticatedCentrosDeCustoRelatorioRouteImport } from './routes/_authenticated/centros-de-custo/relatorio'
import { Route as AuthenticatedAnalisesIndicadoresRouteImport } from './routes/_authenticated/analises/indicadores'
import { Route as AuthenticatedMasterEmpresasIndexRouteImport } from './routes/_authenticated/master/empresas/index'
import { Route as AuthenticatedMasterEmpresasNovaRouteImport } from './routes/_authenticated/master/empresas/nova'
import { Route as AuthenticatedMasterEmpresasIdRouteImport } from './routes/_authenticated/master/empresas/$id'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjecaoRoute = AuthenticatedProjecaoRouteImport.update({
  id: '/projecao',
  path: '/projecao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCobrancasRoute = AuthenticatedCobrancasRouteImport.update({
  id: '/cobrancas',
  path: '/cobrancas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMasterRouteRoute =
  AuthenticatedMasterRouteRouteImport.update({
    id: '/master',
    path: '/master',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContadorRouteRoute =
  AuthenticatedContadorRouteRouteImport.update({
    id: '/contador',
    path: '/contador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosDeCustoRouteRoute =
  AuthenticatedCentrosDeCustoRouteRouteImport.update({
    id: '/centros-de-custo',
    path: '/centros-de-custo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterIndexRoute =
  AuthenticatedMasterIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedConfiguracoesIndexRoute =
  AuthenticatedConfiguracoesIndexRouteImport.update({
    id: '/configuracoes/',
    path: '/configuracoes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosDeCustoIndexRoute =
  AuthenticatedCentrosDeCustoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCentrosDeCustoRouteRoute,
  } as any)
const AuthenticatedVendasProdutosRoute =
  AuthenticatedVendasProdutosRouteImport.update({
    id: '/vendas/produtos',
    path: '/vendas/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasPedidosRoute =
  AuthenticatedVendasPedidosRouteImport.update({
    id: '/vendas/pedidos',
    path: '/vendas/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasClientesRoute =
  AuthenticatedVendasClientesRouteImport.update({
    id: '/vendas/clientes',
    path: '/vendas/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterConvitesRoute =
  AuthenticatedMasterConvitesRouteImport.update({
    id: '/convites',
    path: '/convites',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedFinanceiroTransacoesRoute =
  AuthenticatedFinanceiroTransacoesRouteImport.update({
    id: '/financeiro/transacoes',
    path: '/financeiro/transacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRegrasNomesRoute =
  AuthenticatedFinanceiroRegrasNomesRouteImport.update({
    id: '/financeiro/regras-nomes',
    path: '/financeiro/regras-nomes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroImportarNfeRoute =
  AuthenticatedFinanceiroImportarNfeRouteImport.update({
    id: '/financeiro/importar-nfe',
    path: '/financeiro/importar-nfe',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroImportarRoute =
  AuthenticatedFinanceiroImportarRouteImport.update({
    id: '/financeiro/importar',
    path: '/financeiro/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroFluxoCaixaRoute =
  AuthenticatedFinanceiroFluxoCaixaRouteImport.update({
    id: '/financeiro/fluxo-caixa',
    path: '/financeiro/fluxo-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasReceberRoute =
  AuthenticatedFinanceiroContasReceberRouteImport.update({
    id: '/financeiro/contas-receber',
    path: '/financeiro/contas-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasPagarRoute =
  AuthenticatedFinanceiroContasPagarRouteImport.update({
    id: '/financeiro/contas-pagar',
    path: '/financeiro/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasBancariasRoute =
  AuthenticatedFinanceiroContasBancariasRouteImport.update({
    id: '/financeiro/contas-bancarias',
    path: '/financeiro/contas-bancarias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoRoute =
  AuthenticatedFinanceiroConciliacaoRouteImport.update({
    id: '/financeiro/conciliacao',
    path: '/financeiro/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroCategoriasRoute =
  AuthenticatedFinanceiroCategoriasRouteImport.update({
    id: '/financeiro/categorias',
    path: '/financeiro/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroCartoesRoute =
  AuthenticatedFinanceiroCartoesRouteImport.update({
    id: '/financeiro/cartoes',
    path: '/financeiro/cartoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroCalendarioRoute =
  AuthenticatedFinanceiroCalendarioRouteImport.update({
    id: '/financeiro/calendario',
    path: '/financeiro/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContadorRelatoriosRoute =
  AuthenticatedContadorRelatoriosRouteImport.update({
    id: '/relatorios',
    path: '/relatorios',
    getParentRoute: () => AuthenticatedContadorRouteRoute,
  } as any)
const AuthenticatedContadorLancamentosRoute =
  AuthenticatedContadorLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedContadorRouteRoute,
  } as any)
const AuthenticatedContadorExportarRoute =
  AuthenticatedContadorExportarRouteImport.update({
    id: '/exportar',
    path: '/exportar',
    getParentRoute: () => AuthenticatedContadorRouteRoute,
  } as any)
const AuthenticatedContadorDashboardRoute =
  AuthenticatedContadorDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedContadorRouteRoute,
  } as any)
const AuthenticatedConfiguracoesUsuariosRoute =
  AuthenticatedConfiguracoesUsuariosRouteImport.update({
    id: '/configuracoes/usuarios',
    path: '/configuracoes/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesPermissoesRoute =
  AuthenticatedConfiguracoesPermissoesRouteImport.update({
    id: '/configuracoes/permissoes',
    path: '/configuracoes/permissoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesPerfilRoute =
  AuthenticatedConfiguracoesPerfilRouteImport.update({
    id: '/configuracoes/perfil',
    path: '/configuracoes/perfil',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesOpenBankingRoute =
  AuthenticatedConfiguracoesOpenBankingRouteImport.update({
    id: '/configuracoes/open-banking',
    path: '/configuracoes/open-banking',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesNotificacoesRoute =
  AuthenticatedConfiguracoesNotificacoesRouteImport.update({
    id: '/configuracoes/notificacoes',
    path: '/configuracoes/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesCobrancasRoute =
  AuthenticatedConfiguracoesCobrancasRouteImport.update({
    id: '/configuracoes/cobrancas',
    path: '/configuracoes/cobrancas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesAprovacoesRoute =
  AuthenticatedConfiguracoesAprovacoesRouteImport.update({
    id: '/configuracoes/aprovacoes',
    path: '/configuracoes/aprovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosDeCustoRelatorioRoute =
  AuthenticatedCentrosDeCustoRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => AuthenticatedCentrosDeCustoRouteRoute,
  } as any)
const AuthenticatedAnalisesIndicadoresRoute =
  AuthenticatedAnalisesIndicadoresRouteImport.update({
    id: '/analises/indicadores',
    path: '/analises/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterEmpresasIndexRoute =
  AuthenticatedMasterEmpresasIndexRouteImport.update({
    id: '/empresas/',
    path: '/empresas/',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedMasterEmpresasNovaRoute =
  AuthenticatedMasterEmpresasNovaRouteImport.update({
    id: '/empresas/nova',
    path: '/empresas/nova',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)
const AuthenticatedMasterEmpresasIdRoute =
  AuthenticatedMasterEmpresasIdRouteImport.update({
    id: '/empresas/$id',
    path: '/empresas/$id',
    getParentRoute: () => AuthenticatedMasterRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/centros-de-custo': typeof AuthenticatedCentrosDeCustoRouteRouteWithChildren
  '/contador': typeof AuthenticatedContadorRouteRouteWithChildren
  '/master': typeof AuthenticatedMasterRouteRouteWithChildren
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/analises/indicadores': typeof AuthenticatedAnalisesIndicadoresRoute
  '/centros-de-custo/relatorio': typeof AuthenticatedCentrosDeCustoRelatorioRoute
  '/configuracoes/aprovacoes': typeof AuthenticatedConfiguracoesAprovacoesRoute
  '/configuracoes/cobrancas': typeof AuthenticatedConfiguracoesCobrancasRoute
  '/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/configuracoes/open-banking': typeof AuthenticatedConfiguracoesOpenBankingRoute
  '/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/contador/dashboard': typeof AuthenticatedContadorDashboardRoute
  '/contador/exportar': typeof AuthenticatedContadorExportarRoute
  '/contador/lancamentos': typeof AuthenticatedContadorLancamentosRoute
  '/contador/relatorios': typeof AuthenticatedContadorRelatoriosRoute
  '/financeiro/calendario': typeof AuthenticatedFinanceiroCalendarioRoute
  '/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/financeiro/categorias': typeof AuthenticatedFinanceiroCategoriasRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/contas-bancarias': typeof AuthenticatedFinanceiroContasBancariasRoute
  '/financeiro/contas-pagar': typeof AuthenticatedFinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof AuthenticatedFinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/financeiro/importar': typeof AuthenticatedFinanceiroImportarRoute
  '/financeiro/importar-nfe': typeof AuthenticatedFinanceiroImportarNfeRoute
  '/financeiro/regras-nomes': typeof AuthenticatedFinanceiroRegrasNomesRoute
  '/financeiro/transacoes': typeof AuthenticatedFinanceiroTransacoesRoute
  '/master/convites': typeof AuthenticatedMasterConvitesRoute
  '/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/vendas/produtos': typeof AuthenticatedVendasProdutosRoute
  '/centros-de-custo/': typeof AuthenticatedCentrosDeCustoIndexRoute
  '/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/master/': typeof AuthenticatedMasterIndexRoute
  '/master/empresas/$id': typeof AuthenticatedMasterEmpresasIdRoute
  '/master/empresas/nova': typeof AuthenticatedMasterEmpresasNovaRoute
  '/master/empresas/': typeof AuthenticatedMasterEmpresasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/contador': typeof AuthenticatedContadorRouteRouteWithChildren
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/cobrancas': typeof AuthenticatedCobrancasRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/analises/indicadores': typeof AuthenticatedAnalisesIndicadoresRoute
  '/centros-de-custo/relatorio': typeof AuthenticatedCentrosDeCustoRelatorioRoute
  '/configuracoes/aprovacoes': typeof AuthenticatedConfiguracoesAprovacoesRoute
  '/configuracoes/cobrancas': typeof AuthenticatedConfiguracoesCobrancasRoute
  '/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/configuracoes/open-banking': typeof AuthenticatedConfiguracoesOpenBankingRoute
  '/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/contador/dashboard': typeof AuthenticatedContadorDashboardRoute
  '/contador/exportar': typeof AuthenticatedContadorExportarRoute
  '/contador/lancamentos': typeof AuthenticatedContadorLancamentosRoute
  '/contador/relatorios': typeof AuthenticatedContadorRelatoriosRoute
  '/financeiro/calendario': typeof AuthenticatedFinanceiroCalendarioRoute
  '/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/financeiro/categorias': typeof AuthenticatedFinanceiroCategoriasRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/contas-bancarias': typeof AuthenticatedFinanceiroContasBancariasRoute
  '/financeiro/contas-pagar': typeof AuthenticatedFinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof AuthenticatedFinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/financeiro/importar': typeof AuthenticatedFinanceiroImportarRoute
  '/financeiro/importar-nfe': typeof AuthenticatedFinanceiroImportarNfeRoute
  '/financeiro/regras-nomes': typeof AuthenticatedFinanceiroRegrasNomesRoute
  '/financeiro/transacoes': typeof AuthenticatedFinanceiroTransacoesRoute
  '/master/convites': typeof AuthenticatedMasterConvitesRoute
  '/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/vendas/produtos': typeof AuthenticatedVendasProdutosRoute
  '/centros-de-custo': typeof AuthenticatedCentrosDeCustoIndexRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesIndexRoute
  '/master': typeof AuthenticatedMasterIndexRoute
  '/master/empresas/$id': typeof AuthenticatedMasterEmpresasIdRoute
  '/master/empresas/nova': typeof AuthenticatedMasterEmpresasNovaRoute
  '/master/empresas': typeof AuthenticatedMasterEmpresasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/centros-de-custo': typeof AuthenticatedCentrosDeCustoRouteRouteWithChildren
  '/_authenticated/contador': typeof AuthenticatedContadorRouteRouteWithChildren
  '/_authenticated/master': typeof AuthenticatedMasterRouteRouteWithChildren
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/cobrancas': typeof AuthenticatedCobrancasRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRoute
  '/_authenticated/projecao': typeof AuthenticatedProjecaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/analises/indicadores': typeof AuthenticatedAnalisesIndicadoresRoute
  '/_authenticated/centros-de-custo/relatorio': typeof AuthenticatedCentrosDeCustoRelatorioRoute
  '/_authenticated/configuracoes/aprovacoes': typeof AuthenticatedConfiguracoesAprovacoesRoute
  '/_authenticated/configuracoes/cobrancas': typeof AuthenticatedConfiguracoesCobrancasRoute
  '/_authenticated/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/_authenticated/configuracoes/open-banking': typeof AuthenticatedConfiguracoesOpenBankingRoute
  '/_authenticated/configuracoes/perfil': typeof AuthenticatedConfiguracoesPerfilRoute
  '/_authenticated/configuracoes/permissoes': typeof AuthenticatedConfiguracoesPermissoesRoute
  '/_authenticated/configuracoes/usuarios': typeof AuthenticatedConfiguracoesUsuariosRoute
  '/_authenticated/contador/dashboard': typeof AuthenticatedContadorDashboardRoute
  '/_authenticated/contador/exportar': typeof AuthenticatedContadorExportarRoute
  '/_authenticated/contador/lancamentos': typeof AuthenticatedContadorLancamentosRoute
  '/_authenticated/contador/relatorios': typeof AuthenticatedContadorRelatoriosRoute
  '/_authenticated/financeiro/calendario': typeof AuthenticatedFinanceiroCalendarioRoute
  '/_authenticated/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/_authenticated/financeiro/categorias': typeof AuthenticatedFinanceiroCategoriasRoute
  '/_authenticated/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/_authenticated/financeiro/contas-bancarias': typeof AuthenticatedFinanceiroContasBancariasRoute
  '/_authenticated/financeiro/contas-pagar': typeof AuthenticatedFinanceiroContasPagarRoute
  '/_authenticated/financeiro/contas-receber': typeof AuthenticatedFinanceiroContasReceberRoute
  '/_authenticated/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/_authenticated/financeiro/importar': typeof AuthenticatedFinanceiroImportarRoute
  '/_authenticated/financeiro/importar-nfe': typeof AuthenticatedFinanceiroImportarNfeRoute
  '/_authenticated/financeiro/regras-nomes': typeof AuthenticatedFinanceiroRegrasNomesRoute
  '/_authenticated/financeiro/transacoes': typeof AuthenticatedFinanceiroTransacoesRoute
  '/_authenticated/master/convites': typeof AuthenticatedMasterConvitesRoute
  '/_authenticated/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/_authenticated/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/_authenticated/vendas/produtos': typeof AuthenticatedVendasProdutosRoute
  '/_authenticated/centros-de-custo/': typeof AuthenticatedCentrosDeCustoIndexRoute
  '/_authenticated/configuracoes/': typeof AuthenticatedConfiguracoesIndexRoute
  '/_authenticated/master/': typeof AuthenticatedMasterIndexRoute
  '/_authenticated/master/empresas/$id': typeof AuthenticatedMasterEmpresasIdRoute
  '/_authenticated/master/empresas/nova': typeof AuthenticatedMasterEmpresasNovaRoute
  '/_authenticated/master/empresas/': typeof AuthenticatedMasterEmpresasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/centros-de-custo'
    | '/contador'
    | '/master'
    | '/aprovacoes'
    | '/cobrancas'
    | '/dashboard'
    | '/notificacoes'
    | '/orcamento'
    | '/projecao'
    | '/relatorios'
    | '/analises/indicadores'
    | '/centros-de-custo/relatorio'
    | '/configuracoes/aprovacoes'
    | '/configuracoes/cobrancas'
    | '/configuracoes/notificacoes'
    | '/configuracoes/open-banking'
    | '/configuracoes/perfil'
    | '/configuracoes/permissoes'
    | '/configuracoes/usuarios'
    | '/contador/dashboard'
    | '/contador/exportar'
    | '/contador/lancamentos'
    | '/contador/relatorios'
    | '/financeiro/calendario'
    | '/financeiro/cartoes'
    | '/financeiro/categorias'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-bancarias'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/importar'
    | '/financeiro/importar-nfe'
    | '/financeiro/regras-nomes'
    | '/financeiro/transacoes'
    | '/master/convites'
    | '/vendas/clientes'
    | '/vendas/pedidos'
    | '/vendas/produtos'
    | '/centros-de-custo/'
    | '/configuracoes/'
    | '/master/'
    | '/master/empresas/$id'
    | '/master/empresas/nova'
    | '/master/empresas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/contador'
    | '/aprovacoes'
    | '/cobrancas'
    | '/dashboard'
    | '/notificacoes'
    | '/orcamento'
    | '/projecao'
    | '/relatorios'
    | '/analises/indicadores'
    | '/centros-de-custo/relatorio'
    | '/configuracoes/aprovacoes'
    | '/configuracoes/cobrancas'
    | '/configuracoes/notificacoes'
    | '/configuracoes/open-banking'
    | '/configuracoes/perfil'
    | '/configuracoes/permissoes'
    | '/configuracoes/usuarios'
    | '/contador/dashboard'
    | '/contador/exportar'
    | '/contador/lancamentos'
    | '/contador/relatorios'
    | '/financeiro/calendario'
    | '/financeiro/cartoes'
    | '/financeiro/categorias'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-bancarias'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/importar'
    | '/financeiro/importar-nfe'
    | '/financeiro/regras-nomes'
    | '/financeiro/transacoes'
    | '/master/convites'
    | '/vendas/clientes'
    | '/vendas/pedidos'
    | '/vendas/produtos'
    | '/centros-de-custo'
    | '/configuracoes'
    | '/master'
    | '/master/empresas/$id'
    | '/master/empresas/nova'
    | '/master/empresas'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/centros-de-custo'
    | '/_authenticated/contador'
    | '/_authenticated/master'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/cobrancas'
    | '/_authenticated/dashboard'
    | '/_authenticated/notificacoes'
    | '/_authenticated/orcamento'
    | '/_authenticated/projecao'
    | '/_authenticated/relatorios'
    | '/_authenticated/analises/indicadores'
    | '/_authenticated/centros-de-custo/relatorio'
    | '/_authenticated/configuracoes/aprovacoes'
    | '/_authenticated/configuracoes/cobrancas'
    | '/_authenticated/configuracoes/notificacoes'
    | '/_authenticated/configuracoes/open-banking'
    | '/_authenticated/configuracoes/perfil'
    | '/_authenticated/configuracoes/permissoes'
    | '/_authenticated/configuracoes/usuarios'
    | '/_authenticated/contador/dashboard'
    | '/_authenticated/contador/exportar'
    | '/_authenticated/contador/lancamentos'
    | '/_authenticated/contador/relatorios'
    | '/_authenticated/financeiro/calendario'
    | '/_authenticated/financeiro/cartoes'
    | '/_authenticated/financeiro/categorias'
    | '/_authenticated/financeiro/conciliacao'
    | '/_authenticated/financeiro/contas-bancarias'
    | '/_authenticated/financeiro/contas-pagar'
    | '/_authenticated/financeiro/contas-receber'
    | '/_authenticated/financeiro/fluxo-caixa'
    | '/_authenticated/financeiro/importar'
    | '/_authenticated/financeiro/importar-nfe'
    | '/_authenticated/financeiro/regras-nomes'
    | '/_authenticated/financeiro/transacoes'
    | '/_authenticated/master/convites'
    | '/_authenticated/vendas/clientes'
    | '/_authenticated/vendas/pedidos'
    | '/_authenticated/vendas/produtos'
    | '/_authenticated/centros-de-custo/'
    | '/_authenticated/configuracoes/'
    | '/_authenticated/master/'
    | '/_authenticated/master/empresas/$id'
    | '/_authenticated/master/empresas/nova'
    | '/_authenticated/master/empresas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projecao': {
      id: '/_authenticated/projecao'
      path: '/projecao'
      fullPath: '/projecao'
      preLoaderRoute: typeof AuthenticatedProjecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cobrancas': {
      id: '/_authenticated/cobrancas'
      path: '/cobrancas'
      fullPath: '/cobrancas'
      preLoaderRoute: typeof AuthenticatedCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master': {
      id: '/_authenticated/master'
      path: '/master'
      fullPath: '/master'
      preLoaderRoute: typeof AuthenticatedMasterRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contador': {
      id: '/_authenticated/contador'
      path: '/contador'
      fullPath: '/contador'
      preLoaderRoute: typeof AuthenticatedContadorRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-de-custo': {
      id: '/_authenticated/centros-de-custo'
      path: '/centros-de-custo'
      fullPath: '/centros-de-custo'
      preLoaderRoute: typeof AuthenticatedCentrosDeCustoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/': {
      id: '/_authenticated/master/'
      path: '/'
      fullPath: '/master/'
      preLoaderRoute: typeof AuthenticatedMasterIndexRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/configuracoes/': {
      id: '/_authenticated/configuracoes/'
      path: '/configuracoes'
      fullPath: '/configuracoes/'
      preLoaderRoute: typeof AuthenticatedConfiguracoesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-de-custo/': {
      id: '/_authenticated/centros-de-custo/'
      path: '/'
      fullPath: '/centros-de-custo/'
      preLoaderRoute: typeof AuthenticatedCentrosDeCustoIndexRouteImport
      parentRoute: typeof AuthenticatedCentrosDeCustoRouteRoute
    }
    '/_authenticated/vendas/produtos': {
      id: '/_authenticated/vendas/produtos'
      path: '/vendas/produtos'
      fullPath: '/vendas/produtos'
      preLoaderRoute: typeof AuthenticatedVendasProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/pedidos': {
      id: '/_authenticated/vendas/pedidos'
      path: '/vendas/pedidos'
      fullPath: '/vendas/pedidos'
      preLoaderRoute: typeof AuthenticatedVendasPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/clientes': {
      id: '/_authenticated/vendas/clientes'
      path: '/vendas/clientes'
      fullPath: '/vendas/clientes'
      preLoaderRoute: typeof AuthenticatedVendasClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/convites': {
      id: '/_authenticated/master/convites'
      path: '/convites'
      fullPath: '/master/convites'
      preLoaderRoute: typeof AuthenticatedMasterConvitesRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/financeiro/transacoes': {
      id: '/_authenticated/financeiro/transacoes'
      path: '/financeiro/transacoes'
      fullPath: '/financeiro/transacoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroTransacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/regras-nomes': {
      id: '/_authenticated/financeiro/regras-nomes'
      path: '/financeiro/regras-nomes'
      fullPath: '/financeiro/regras-nomes'
      preLoaderRoute: typeof AuthenticatedFinanceiroRegrasNomesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/importar-nfe': {
      id: '/_authenticated/financeiro/importar-nfe'
      path: '/financeiro/importar-nfe'
      fullPath: '/financeiro/importar-nfe'
      preLoaderRoute: typeof AuthenticatedFinanceiroImportarNfeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/importar': {
      id: '/_authenticated/financeiro/importar'
      path: '/financeiro/importar'
      fullPath: '/financeiro/importar'
      preLoaderRoute: typeof AuthenticatedFinanceiroImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/fluxo-caixa': {
      id: '/_authenticated/financeiro/fluxo-caixa'
      path: '/financeiro/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-receber': {
      id: '/_authenticated/financeiro/contas-receber'
      path: '/financeiro/contas-receber'
      fullPath: '/financeiro/contas-receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-pagar': {
      id: '/_authenticated/financeiro/contas-pagar'
      path: '/financeiro/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-bancarias': {
      id: '/_authenticated/financeiro/contas-bancarias'
      path: '/financeiro/contas-bancarias'
      fullPath: '/financeiro/contas-bancarias'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasBancariasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/conciliacao': {
      id: '/_authenticated/financeiro/conciliacao'
      path: '/financeiro/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/categorias': {
      id: '/_authenticated/financeiro/categorias'
      path: '/financeiro/categorias'
      fullPath: '/financeiro/categorias'
      preLoaderRoute: typeof AuthenticatedFinanceiroCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/cartoes': {
      id: '/_authenticated/financeiro/cartoes'
      path: '/financeiro/cartoes'
      fullPath: '/financeiro/cartoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroCartoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/calendario': {
      id: '/_authenticated/financeiro/calendario'
      path: '/financeiro/calendario'
      fullPath: '/financeiro/calendario'
      preLoaderRoute: typeof AuthenticatedFinanceiroCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contador/relatorios': {
      id: '/_authenticated/contador/relatorios'
      path: '/relatorios'
      fullPath: '/contador/relatorios'
      preLoaderRoute: typeof AuthenticatedContadorRelatoriosRouteImport
      parentRoute: typeof AuthenticatedContadorRouteRoute
    }
    '/_authenticated/contador/lancamentos': {
      id: '/_authenticated/contador/lancamentos'
      path: '/lancamentos'
      fullPath: '/contador/lancamentos'
      preLoaderRoute: typeof AuthenticatedContadorLancamentosRouteImport
      parentRoute: typeof AuthenticatedContadorRouteRoute
    }
    '/_authenticated/contador/exportar': {
      id: '/_authenticated/contador/exportar'
      path: '/exportar'
      fullPath: '/contador/exportar'
      preLoaderRoute: typeof AuthenticatedContadorExportarRouteImport
      parentRoute: typeof AuthenticatedContadorRouteRoute
    }
    '/_authenticated/contador/dashboard': {
      id: '/_authenticated/contador/dashboard'
      path: '/dashboard'
      fullPath: '/contador/dashboard'
      preLoaderRoute: typeof AuthenticatedContadorDashboardRouteImport
      parentRoute: typeof AuthenticatedContadorRouteRoute
    }
    '/_authenticated/configuracoes/usuarios': {
      id: '/_authenticated/configuracoes/usuarios'
      path: '/configuracoes/usuarios'
      fullPath: '/configuracoes/usuarios'
      preLoaderRoute: typeof AuthenticatedConfiguracoesUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/permissoes': {
      id: '/_authenticated/configuracoes/permissoes'
      path: '/configuracoes/permissoes'
      fullPath: '/configuracoes/permissoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPermissoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/perfil': {
      id: '/_authenticated/configuracoes/perfil'
      path: '/configuracoes/perfil'
      fullPath: '/configuracoes/perfil'
      preLoaderRoute: typeof AuthenticatedConfiguracoesPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/open-banking': {
      id: '/_authenticated/configuracoes/open-banking'
      path: '/configuracoes/open-banking'
      fullPath: '/configuracoes/open-banking'
      preLoaderRoute: typeof AuthenticatedConfiguracoesOpenBankingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/notificacoes': {
      id: '/_authenticated/configuracoes/notificacoes'
      path: '/configuracoes/notificacoes'
      fullPath: '/configuracoes/notificacoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/cobrancas': {
      id: '/_authenticated/configuracoes/cobrancas'
      path: '/configuracoes/cobrancas'
      fullPath: '/configuracoes/cobrancas'
      preLoaderRoute: typeof AuthenticatedConfiguracoesCobrancasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/aprovacoes': {
      id: '/_authenticated/configuracoes/aprovacoes'
      path: '/configuracoes/aprovacoes'
      fullPath: '/configuracoes/aprovacoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-de-custo/relatorio': {
      id: '/_authenticated/centros-de-custo/relatorio'
      path: '/relatorio'
      fullPath: '/centros-de-custo/relatorio'
      preLoaderRoute: typeof AuthenticatedCentrosDeCustoRelatorioRouteImport
      parentRoute: typeof AuthenticatedCentrosDeCustoRouteRoute
    }
    '/_authenticated/analises/indicadores': {
      id: '/_authenticated/analises/indicadores'
      path: '/analises/indicadores'
      fullPath: '/analises/indicadores'
      preLoaderRoute: typeof AuthenticatedAnalisesIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master/empresas/': {
      id: '/_authenticated/master/empresas/'
      path: '/empresas'
      fullPath: '/master/empresas/'
      preLoaderRoute: typeof AuthenticatedMasterEmpresasIndexRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/master/empresas/nova': {
      id: '/_authenticated/master/empresas/nova'
      path: '/empresas/nova'
      fullPath: '/master/empresas/nova'
      preLoaderRoute: typeof AuthenticatedMasterEmpresasNovaRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
    '/_authenticated/master/empresas/$id': {
      id: '/_authenticated/master/empresas/$id'
      path: '/empresas/$id'
      fullPath: '/master/empresas/$id'
      preLoaderRoute: typeof AuthenticatedMasterEmpresasIdRouteImport
      parentRoute: typeof AuthenticatedMasterRouteRoute
    }
  }
}

interface AuthenticatedCentrosDeCustoRouteRouteChildren {
  AuthenticatedCentrosDeCustoRelatorioRoute: typeof AuthenticatedCentrosDeCustoRelatorioRoute
  AuthenticatedCentrosDeCustoIndexRoute: typeof AuthenticatedCentrosDeCustoIndexRoute
}

const AuthenticatedCentrosDeCustoRouteRouteChildren: AuthenticatedCentrosDeCustoRouteRouteChildren =
  {
    AuthenticatedCentrosDeCustoRelatorioRoute:
      AuthenticatedCentrosDeCustoRelatorioRoute,
    AuthenticatedCentrosDeCustoIndexRoute:
      AuthenticatedCentrosDeCustoIndexRoute,
  }

const AuthenticatedCentrosDeCustoRouteRouteWithChildren =
  AuthenticatedCentrosDeCustoRouteRoute._addFileChildren(
    AuthenticatedCentrosDeCustoRouteRouteChildren,
  )

interface AuthenticatedContadorRouteRouteChildren {
  AuthenticatedContadorDashboardRoute: typeof AuthenticatedContadorDashboardRoute
  AuthenticatedContadorExportarRoute: typeof AuthenticatedContadorExportarRoute
  AuthenticatedContadorLancamentosRoute: typeof AuthenticatedContadorLancamentosRoute
  AuthenticatedContadorRelatoriosRoute: typeof AuthenticatedContadorRelatoriosRoute
}

const AuthenticatedContadorRouteRouteChildren: AuthenticatedContadorRouteRouteChildren =
  {
    AuthenticatedContadorDashboardRoute: AuthenticatedContadorDashboardRoute,
    AuthenticatedContadorExportarRoute: AuthenticatedContadorExportarRoute,
    AuthenticatedContadorLancamentosRoute:
      AuthenticatedContadorLancamentosRoute,
    AuthenticatedContadorRelatoriosRoute: AuthenticatedContadorRelatoriosRoute,
  }

const AuthenticatedContadorRouteRouteWithChildren =
  AuthenticatedContadorRouteRoute._addFileChildren(
    AuthenticatedContadorRouteRouteChildren,
  )

interface AuthenticatedMasterRouteRouteChildren {
  AuthenticatedMasterConvitesRoute: typeof AuthenticatedMasterConvitesRoute
  AuthenticatedMasterIndexRoute: typeof AuthenticatedMasterIndexRoute
  AuthenticatedMasterEmpresasIdRoute: typeof AuthenticatedMasterEmpresasIdRoute
  AuthenticatedMasterEmpresasNovaRoute: typeof AuthenticatedMasterEmpresasNovaRoute
  AuthenticatedMasterEmpresasIndexRoute: typeof AuthenticatedMasterEmpresasIndexRoute
}

const AuthenticatedMasterRouteRouteChildren: AuthenticatedMasterRouteRouteChildren =
  {
    AuthenticatedMasterConvitesRoute: AuthenticatedMasterConvitesRoute,
    AuthenticatedMasterIndexRoute: AuthenticatedMasterIndexRoute,
    AuthenticatedMasterEmpresasIdRoute: AuthenticatedMasterEmpresasIdRoute,
    AuthenticatedMasterEmpresasNovaRoute: AuthenticatedMasterEmpresasNovaRoute,
    AuthenticatedMasterEmpresasIndexRoute:
      AuthenticatedMasterEmpresasIndexRoute,
  }

const AuthenticatedMasterRouteRouteWithChildren =
  AuthenticatedMasterRouteRoute._addFileChildren(
    AuthenticatedMasterRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCentrosDeCustoRouteRoute: typeof AuthenticatedCentrosDeCustoRouteRouteWithChildren
  AuthenticatedContadorRouteRoute: typeof AuthenticatedContadorRouteRouteWithChildren
  AuthenticatedMasterRouteRoute: typeof AuthenticatedMasterRouteRouteWithChildren
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedCobrancasRoute: typeof AuthenticatedCobrancasRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRoute
  AuthenticatedProjecaoRoute: typeof AuthenticatedProjecaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedAnalisesIndicadoresRoute: typeof AuthenticatedAnalisesIndicadoresRoute
  AuthenticatedConfiguracoesAprovacoesRoute: typeof AuthenticatedConfiguracoesAprovacoesRoute
  AuthenticatedConfiguracoesCobrancasRoute: typeof AuthenticatedConfiguracoesCobrancasRoute
  AuthenticatedConfiguracoesNotificacoesRoute: typeof AuthenticatedConfiguracoesNotificacoesRoute
  AuthenticatedConfiguracoesOpenBankingRoute: typeof AuthenticatedConfiguracoesOpenBankingRoute
  AuthenticatedConfiguracoesPerfilRoute: typeof AuthenticatedConfiguracoesPerfilRoute
  AuthenticatedConfiguracoesPermissoesRoute: typeof AuthenticatedConfiguracoesPermissoesRoute
  AuthenticatedConfiguracoesUsuariosRoute: typeof AuthenticatedConfiguracoesUsuariosRoute
  AuthenticatedFinanceiroCalendarioRoute: typeof AuthenticatedFinanceiroCalendarioRoute
  AuthenticatedFinanceiroCartoesRoute: typeof AuthenticatedFinanceiroCartoesRoute
  AuthenticatedFinanceiroCategoriasRoute: typeof AuthenticatedFinanceiroCategoriasRoute
  AuthenticatedFinanceiroConciliacaoRoute: typeof AuthenticatedFinanceiroConciliacaoRoute
  AuthenticatedFinanceiroContasBancariasRoute: typeof AuthenticatedFinanceiroContasBancariasRoute
  AuthenticatedFinanceiroContasPagarRoute: typeof AuthenticatedFinanceiroContasPagarRoute
  AuthenticatedFinanceiroContasReceberRoute: typeof AuthenticatedFinanceiroContasReceberRoute
  AuthenticatedFinanceiroFluxoCaixaRoute: typeof AuthenticatedFinanceiroFluxoCaixaRoute
  AuthenticatedFinanceiroImportarRoute: typeof AuthenticatedFinanceiroImportarRoute
  AuthenticatedFinanceiroImportarNfeRoute: typeof AuthenticatedFinanceiroImportarNfeRoute
  AuthenticatedFinanceiroRegrasNomesRoute: typeof AuthenticatedFinanceiroRegrasNomesRoute
  AuthenticatedFinanceiroTransacoesRoute: typeof AuthenticatedFinanceiroTransacoesRoute
  AuthenticatedVendasClientesRoute: typeof AuthenticatedVendasClientesRoute
  AuthenticatedVendasPedidosRoute: typeof AuthenticatedVendasPedidosRoute
  AuthenticatedVendasProdutosRoute: typeof AuthenticatedVendasProdutosRoute
  AuthenticatedConfiguracoesIndexRoute: typeof AuthenticatedConfiguracoesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCentrosDeCustoRouteRoute:
    AuthenticatedCentrosDeCustoRouteRouteWithChildren,
  AuthenticatedContadorRouteRoute: AuthenticatedContadorRouteRouteWithChildren,
  AuthenticatedMasterRouteRoute: AuthenticatedMasterRouteRouteWithChildren,
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedCobrancasRoute: AuthenticatedCobrancasRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRoute,
  AuthenticatedProjecaoRoute: AuthenticatedProjecaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedAnalisesIndicadoresRoute: AuthenticatedAnalisesIndicadoresRoute,
  AuthenticatedConfiguracoesAprovacoesRoute:
    AuthenticatedConfiguracoesAprovacoesRoute,
  AuthenticatedConfiguracoesCobrancasRoute:
    AuthenticatedConfiguracoesCobrancasRoute,
  AuthenticatedConfiguracoesNotificacoesRoute:
    AuthenticatedConfiguracoesNotificacoesRoute,
  AuthenticatedConfiguracoesOpenBankingRoute:
    AuthenticatedConfiguracoesOpenBankingRoute,
  AuthenticatedConfiguracoesPerfilRoute: AuthenticatedConfiguracoesPerfilRoute,
  AuthenticatedConfiguracoesPermissoesRoute:
    AuthenticatedConfiguracoesPermissoesRoute,
  AuthenticatedConfiguracoesUsuariosRoute:
    AuthenticatedConfiguracoesUsuariosRoute,
  AuthenticatedFinanceiroCalendarioRoute:
    AuthenticatedFinanceiroCalendarioRoute,
  AuthenticatedFinanceiroCartoesRoute: AuthenticatedFinanceiroCartoesRoute,
  AuthenticatedFinanceiroCategoriasRoute:
    AuthenticatedFinanceiroCategoriasRoute,
  AuthenticatedFinanceiroConciliacaoRoute:
    AuthenticatedFinanceiroConciliacaoRoute,
  AuthenticatedFinanceiroContasBancariasRoute:
    AuthenticatedFinanceiroContasBancariasRoute,
  AuthenticatedFinanceiroContasPagarRoute:
    AuthenticatedFinanceiroContasPagarRoute,
  AuthenticatedFinanceiroContasReceberRoute:
    AuthenticatedFinanceiroContasReceberRoute,
  AuthenticatedFinanceiroFluxoCaixaRoute:
    AuthenticatedFinanceiroFluxoCaixaRoute,
  AuthenticatedFinanceiroImportarRoute: AuthenticatedFinanceiroImportarRoute,
  AuthenticatedFinanceiroImportarNfeRoute:
    AuthenticatedFinanceiroImportarNfeRoute,
  AuthenticatedFinanceiroRegrasNomesRoute:
    AuthenticatedFinanceiroRegrasNomesRoute,
  AuthenticatedFinanceiroTransacoesRoute:
    AuthenticatedFinanceiroTransacoesRoute,
  AuthenticatedVendasClientesRoute: AuthenticatedVendasClientesRoute,
  AuthenticatedVendasPedidosRoute: AuthenticatedVendasPedidosRoute,
  AuthenticatedVendasProdutosRoute: AuthenticatedVendasProdutosRoute,
  AuthenticatedConfiguracoesIndexRoute: AuthenticatedConfiguracoesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
