/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProjecaoRouteImport } from './routes/_authenticated/projecao'
import { Route as AuthenticatedOrcamentoRouteImport } from './routes/_authenticated/orcamento'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAprovacoesRouteImport } from './routes/_authenticated/aprovacoes'
import { Route as AuthenticatedCentrosDeCustoRouteRouteImport } from './routes/_authenticated/centros-de-custo/route'
import { Route as AuthenticatedCentrosDeCustoIndexRouteImport } from './routes/_authenticated/centros-de-custo/index'
import { Route as AuthenticatedVendasProdutosRouteImport } from './routes/_authenticated/vendas/produtos'
import { Route as AuthenticatedVendasPedidosRouteImport } from './routes/_authenticated/vendas/pedidos'
import { Route as AuthenticatedVendasClientesRouteImport } from './routes/_authenticated/vendas/clientes'
import { Route as AuthenticatedFinanceiroTransacoesRouteImport } from './routes/_authenticated/financeiro/transacoes'
import { Route as AuthenticatedFinanceiroRegrasNomesRouteImport } from './routes/_authenticated/financeiro/regras-nomes'
import { Route as AuthenticatedFinanceiroImportarRouteImport } from './routes/_authenticated/financeiro/importar'
import { Route as AuthenticatedFinanceiroFluxoCaixaRouteImport } from './routes/_authenticated/financeiro/fluxo-caixa'
import { Route as AuthenticatedFinanceiroContasReceberRouteImport } from './routes/_authenticated/financeiro/contas-receber'
import { Route as AuthenticatedFinanceiroContasPagarRouteImport } from './routes/_authenticated/financeiro/contas-pagar'
import { Route as AuthenticatedFinanceiroContasBancariasRouteImport } from './routes/_authenticated/financeiro/contas-bancarias'
import { Route as AuthenticatedFinanceiroConciliacaoRouteImport } from './routes/_authenticated/financeiro/conciliacao'
import { Route as AuthenticatedFinanceiroCategoriasRouteImport } from './routes/_authenticated/financeiro/categorias'
import { Route as AuthenticatedFinanceiroCartoesRouteImport } from './routes/_authenticated/financeiro/cartoes'
import { Route as AuthenticatedFinanceiroCalendarioRouteImport } from './routes/_authenticated/financeiro/calendario'
import { Route as AuthenticatedConfiguracoesNotificacoesRouteImport } from './routes/_authenticated/configuracoes/notificacoes'
import { Route as AuthenticatedConfiguracoesAprovacoesRouteImport } from './routes/_authenticated/configuracoes/aprovacoes'
import { Route as AuthenticatedCentrosDeCustoRelatorioRouteImport } from './routes/_authenticated/centros-de-custo/relatorio'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProjecaoRoute = AuthenticatedProjecaoRouteImport.update({
  id: '/projecao',
  path: '/projecao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrcamentoRoute = AuthenticatedOrcamentoRouteImport.update({
  id: '/orcamento',
  path: '/orcamento',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAprovacoesRoute = AuthenticatedAprovacoesRouteImport.update({
  id: '/aprovacoes',
  path: '/aprovacoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCentrosDeCustoRouteRoute =
  AuthenticatedCentrosDeCustoRouteRouteImport.update({
    id: '/centros-de-custo',
    path: '/centros-de-custo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosDeCustoIndexRoute =
  AuthenticatedCentrosDeCustoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCentrosDeCustoRouteRoute,
  } as any)
const AuthenticatedVendasProdutosRoute =
  AuthenticatedVendasProdutosRouteImport.update({
    id: '/vendas/produtos',
    path: '/vendas/produtos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasPedidosRoute =
  AuthenticatedVendasPedidosRouteImport.update({
    id: '/vendas/pedidos',
    path: '/vendas/pedidos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVendasClientesRoute =
  AuthenticatedVendasClientesRouteImport.update({
    id: '/vendas/clientes',
    path: '/vendas/clientes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroTransacoesRoute =
  AuthenticatedFinanceiroTransacoesRouteImport.update({
    id: '/financeiro/transacoes',
    path: '/financeiro/transacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRegrasNomesRoute =
  AuthenticatedFinanceiroRegrasNomesRouteImport.update({
    id: '/financeiro/regras-nomes',
    path: '/financeiro/regras-nomes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroImportarRoute =
  AuthenticatedFinanceiroImportarRouteImport.update({
    id: '/financeiro/importar',
    path: '/financeiro/importar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroFluxoCaixaRoute =
  AuthenticatedFinanceiroFluxoCaixaRouteImport.update({
    id: '/financeiro/fluxo-caixa',
    path: '/financeiro/fluxo-caixa',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasReceberRoute =
  AuthenticatedFinanceiroContasReceberRouteImport.update({
    id: '/financeiro/contas-receber',
    path: '/financeiro/contas-receber',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasPagarRoute =
  AuthenticatedFinanceiroContasPagarRouteImport.update({
    id: '/financeiro/contas-pagar',
    path: '/financeiro/contas-pagar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroContasBancariasRoute =
  AuthenticatedFinanceiroContasBancariasRouteImport.update({
    id: '/financeiro/contas-bancarias',
    path: '/financeiro/contas-bancarias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroConciliacaoRoute =
  AuthenticatedFinanceiroConciliacaoRouteImport.update({
    id: '/financeiro/conciliacao',
    path: '/financeiro/conciliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroCategoriasRoute =
  AuthenticatedFinanceiroCategoriasRouteImport.update({
    id: '/financeiro/categorias',
    path: '/financeiro/categorias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroCartoesRoute =
  AuthenticatedFinanceiroCartoesRouteImport.update({
    id: '/financeiro/cartoes',
    path: '/financeiro/cartoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroCalendarioRoute =
  AuthenticatedFinanceiroCalendarioRouteImport.update({
    id: '/financeiro/calendario',
    path: '/financeiro/calendario',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesNotificacoesRoute =
  AuthenticatedConfiguracoesNotificacoesRouteImport.update({
    id: '/configuracoes/notificacoes',
    path: '/configuracoes/notificacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedConfiguracoesAprovacoesRoute =
  AuthenticatedConfiguracoesAprovacoesRouteImport.update({
    id: '/configuracoes/aprovacoes',
    path: '/configuracoes/aprovacoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCentrosDeCustoRelatorioRoute =
  AuthenticatedCentrosDeCustoRelatorioRouteImport.update({
    id: '/relatorio',
    path: '/relatorio',
    getParentRoute: () => AuthenticatedCentrosDeCustoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/centros-de-custo': typeof AuthenticatedCentrosDeCustoRouteRouteWithChildren
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/centros-de-custo/relatorio': typeof AuthenticatedCentrosDeCustoRelatorioRoute
  '/configuracoes/aprovacoes': typeof AuthenticatedConfiguracoesAprovacoesRoute
  '/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/financeiro/calendario': typeof AuthenticatedFinanceiroCalendarioRoute
  '/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/financeiro/categorias': typeof AuthenticatedFinanceiroCategoriasRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/contas-bancarias': typeof AuthenticatedFinanceiroContasBancariasRoute
  '/financeiro/contas-pagar': typeof AuthenticatedFinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof AuthenticatedFinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/financeiro/importar': typeof AuthenticatedFinanceiroImportarRoute
  '/financeiro/regras-nomes': typeof AuthenticatedFinanceiroRegrasNomesRoute
  '/financeiro/transacoes': typeof AuthenticatedFinanceiroTransacoesRoute
  '/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/vendas/produtos': typeof AuthenticatedVendasProdutosRoute
  '/centros-de-custo/': typeof AuthenticatedCentrosDeCustoIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/orcamento': typeof AuthenticatedOrcamentoRoute
  '/projecao': typeof AuthenticatedProjecaoRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/centros-de-custo/relatorio': typeof AuthenticatedCentrosDeCustoRelatorioRoute
  '/configuracoes/aprovacoes': typeof AuthenticatedConfiguracoesAprovacoesRoute
  '/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/financeiro/calendario': typeof AuthenticatedFinanceiroCalendarioRoute
  '/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/financeiro/categorias': typeof AuthenticatedFinanceiroCategoriasRoute
  '/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/financeiro/contas-bancarias': typeof AuthenticatedFinanceiroContasBancariasRoute
  '/financeiro/contas-pagar': typeof AuthenticatedFinanceiroContasPagarRoute
  '/financeiro/contas-receber': typeof AuthenticatedFinanceiroContasReceberRoute
  '/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/financeiro/importar': typeof AuthenticatedFinanceiroImportarRoute
  '/financeiro/regras-nomes': typeof AuthenticatedFinanceiroRegrasNomesRoute
  '/financeiro/transacoes': typeof AuthenticatedFinanceiroTransacoesRoute
  '/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/vendas/produtos': typeof AuthenticatedVendasProdutosRoute
  '/centros-de-custo': typeof AuthenticatedCentrosDeCustoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/centros-de-custo': typeof AuthenticatedCentrosDeCustoRouteRouteWithChildren
  '/_authenticated/aprovacoes': typeof AuthenticatedAprovacoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/orcamento': typeof AuthenticatedOrcamentoRoute
  '/_authenticated/projecao': typeof AuthenticatedProjecaoRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/centros-de-custo/relatorio': typeof AuthenticatedCentrosDeCustoRelatorioRoute
  '/_authenticated/configuracoes/aprovacoes': typeof AuthenticatedConfiguracoesAprovacoesRoute
  '/_authenticated/configuracoes/notificacoes': typeof AuthenticatedConfiguracoesNotificacoesRoute
  '/_authenticated/financeiro/calendario': typeof AuthenticatedFinanceiroCalendarioRoute
  '/_authenticated/financeiro/cartoes': typeof AuthenticatedFinanceiroCartoesRoute
  '/_authenticated/financeiro/categorias': typeof AuthenticatedFinanceiroCategoriasRoute
  '/_authenticated/financeiro/conciliacao': typeof AuthenticatedFinanceiroConciliacaoRoute
  '/_authenticated/financeiro/contas-bancarias': typeof AuthenticatedFinanceiroContasBancariasRoute
  '/_authenticated/financeiro/contas-pagar': typeof AuthenticatedFinanceiroContasPagarRoute
  '/_authenticated/financeiro/contas-receber': typeof AuthenticatedFinanceiroContasReceberRoute
  '/_authenticated/financeiro/fluxo-caixa': typeof AuthenticatedFinanceiroFluxoCaixaRoute
  '/_authenticated/financeiro/importar': typeof AuthenticatedFinanceiroImportarRoute
  '/_authenticated/financeiro/regras-nomes': typeof AuthenticatedFinanceiroRegrasNomesRoute
  '/_authenticated/financeiro/transacoes': typeof AuthenticatedFinanceiroTransacoesRoute
  '/_authenticated/vendas/clientes': typeof AuthenticatedVendasClientesRoute
  '/_authenticated/vendas/pedidos': typeof AuthenticatedVendasPedidosRoute
  '/_authenticated/vendas/produtos': typeof AuthenticatedVendasProdutosRoute
  '/_authenticated/centros-de-custo/': typeof AuthenticatedCentrosDeCustoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/centros-de-custo'
    | '/aprovacoes'
    | '/dashboard'
    | '/notificacoes'
    | '/orcamento'
    | '/projecao'
    | '/relatorios'
    | '/centros-de-custo/relatorio'
    | '/configuracoes/aprovacoes'
    | '/configuracoes/notificacoes'
    | '/financeiro/calendario'
    | '/financeiro/cartoes'
    | '/financeiro/categorias'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-bancarias'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/importar'
    | '/financeiro/regras-nomes'
    | '/financeiro/transacoes'
    | '/vendas/clientes'
    | '/vendas/pedidos'
    | '/vendas/produtos'
    | '/centros-de-custo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/onboarding'
    | '/aprovacoes'
    | '/dashboard'
    | '/notificacoes'
    | '/orcamento'
    | '/projecao'
    | '/relatorios'
    | '/centros-de-custo/relatorio'
    | '/configuracoes/aprovacoes'
    | '/configuracoes/notificacoes'
    | '/financeiro/calendario'
    | '/financeiro/cartoes'
    | '/financeiro/categorias'
    | '/financeiro/conciliacao'
    | '/financeiro/contas-bancarias'
    | '/financeiro/contas-pagar'
    | '/financeiro/contas-receber'
    | '/financeiro/fluxo-caixa'
    | '/financeiro/importar'
    | '/financeiro/regras-nomes'
    | '/financeiro/transacoes'
    | '/vendas/clientes'
    | '/vendas/pedidos'
    | '/vendas/produtos'
    | '/centros-de-custo'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/onboarding'
    | '/_authenticated/centros-de-custo'
    | '/_authenticated/aprovacoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/notificacoes'
    | '/_authenticated/orcamento'
    | '/_authenticated/projecao'
    | '/_authenticated/relatorios'
    | '/_authenticated/centros-de-custo/relatorio'
    | '/_authenticated/configuracoes/aprovacoes'
    | '/_authenticated/configuracoes/notificacoes'
    | '/_authenticated/financeiro/calendario'
    | '/_authenticated/financeiro/cartoes'
    | '/_authenticated/financeiro/categorias'
    | '/_authenticated/financeiro/conciliacao'
    | '/_authenticated/financeiro/contas-bancarias'
    | '/_authenticated/financeiro/contas-pagar'
    | '/_authenticated/financeiro/contas-receber'
    | '/_authenticated/financeiro/fluxo-caixa'
    | '/_authenticated/financeiro/importar'
    | '/_authenticated/financeiro/regras-nomes'
    | '/_authenticated/financeiro/transacoes'
    | '/_authenticated/vendas/clientes'
    | '/_authenticated/vendas/pedidos'
    | '/_authenticated/vendas/produtos'
    | '/_authenticated/centros-de-custo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projecao': {
      id: '/_authenticated/projecao'
      path: '/projecao'
      fullPath: '/projecao'
      preLoaderRoute: typeof AuthenticatedProjecaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orcamento': {
      id: '/_authenticated/orcamento'
      path: '/orcamento'
      fullPath: '/orcamento'
      preLoaderRoute: typeof AuthenticatedOrcamentoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/aprovacoes': {
      id: '/_authenticated/aprovacoes'
      path: '/aprovacoes'
      fullPath: '/aprovacoes'
      preLoaderRoute: typeof AuthenticatedAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-de-custo': {
      id: '/_authenticated/centros-de-custo'
      path: '/centros-de-custo'
      fullPath: '/centros-de-custo'
      preLoaderRoute: typeof AuthenticatedCentrosDeCustoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-de-custo/': {
      id: '/_authenticated/centros-de-custo/'
      path: '/'
      fullPath: '/centros-de-custo/'
      preLoaderRoute: typeof AuthenticatedCentrosDeCustoIndexRouteImport
      parentRoute: typeof AuthenticatedCentrosDeCustoRouteRoute
    }
    '/_authenticated/vendas/produtos': {
      id: '/_authenticated/vendas/produtos'
      path: '/vendas/produtos'
      fullPath: '/vendas/produtos'
      preLoaderRoute: typeof AuthenticatedVendasProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/pedidos': {
      id: '/_authenticated/vendas/pedidos'
      path: '/vendas/pedidos'
      fullPath: '/vendas/pedidos'
      preLoaderRoute: typeof AuthenticatedVendasPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vendas/clientes': {
      id: '/_authenticated/vendas/clientes'
      path: '/vendas/clientes'
      fullPath: '/vendas/clientes'
      preLoaderRoute: typeof AuthenticatedVendasClientesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/transacoes': {
      id: '/_authenticated/financeiro/transacoes'
      path: '/financeiro/transacoes'
      fullPath: '/financeiro/transacoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroTransacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/regras-nomes': {
      id: '/_authenticated/financeiro/regras-nomes'
      path: '/financeiro/regras-nomes'
      fullPath: '/financeiro/regras-nomes'
      preLoaderRoute: typeof AuthenticatedFinanceiroRegrasNomesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/importar': {
      id: '/_authenticated/financeiro/importar'
      path: '/financeiro/importar'
      fullPath: '/financeiro/importar'
      preLoaderRoute: typeof AuthenticatedFinanceiroImportarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/fluxo-caixa': {
      id: '/_authenticated/financeiro/fluxo-caixa'
      path: '/financeiro/fluxo-caixa'
      fullPath: '/financeiro/fluxo-caixa'
      preLoaderRoute: typeof AuthenticatedFinanceiroFluxoCaixaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-receber': {
      id: '/_authenticated/financeiro/contas-receber'
      path: '/financeiro/contas-receber'
      fullPath: '/financeiro/contas-receber'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasReceberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-pagar': {
      id: '/_authenticated/financeiro/contas-pagar'
      path: '/financeiro/contas-pagar'
      fullPath: '/financeiro/contas-pagar'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasPagarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/contas-bancarias': {
      id: '/_authenticated/financeiro/contas-bancarias'
      path: '/financeiro/contas-bancarias'
      fullPath: '/financeiro/contas-bancarias'
      preLoaderRoute: typeof AuthenticatedFinanceiroContasBancariasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/conciliacao': {
      id: '/_authenticated/financeiro/conciliacao'
      path: '/financeiro/conciliacao'
      fullPath: '/financeiro/conciliacao'
      preLoaderRoute: typeof AuthenticatedFinanceiroConciliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/categorias': {
      id: '/_authenticated/financeiro/categorias'
      path: '/financeiro/categorias'
      fullPath: '/financeiro/categorias'
      preLoaderRoute: typeof AuthenticatedFinanceiroCategoriasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/cartoes': {
      id: '/_authenticated/financeiro/cartoes'
      path: '/financeiro/cartoes'
      fullPath: '/financeiro/cartoes'
      preLoaderRoute: typeof AuthenticatedFinanceiroCartoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro/calendario': {
      id: '/_authenticated/financeiro/calendario'
      path: '/financeiro/calendario'
      fullPath: '/financeiro/calendario'
      preLoaderRoute: typeof AuthenticatedFinanceiroCalendarioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/notificacoes': {
      id: '/_authenticated/configuracoes/notificacoes'
      path: '/configuracoes/notificacoes'
      fullPath: '/configuracoes/notificacoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes/aprovacoes': {
      id: '/_authenticated/configuracoes/aprovacoes'
      path: '/configuracoes/aprovacoes'
      fullPath: '/configuracoes/aprovacoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesAprovacoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/centros-de-custo/relatorio': {
      id: '/_authenticated/centros-de-custo/relatorio'
      path: '/relatorio'
      fullPath: '/centros-de-custo/relatorio'
      preLoaderRoute: typeof AuthenticatedCentrosDeCustoRelatorioRouteImport
      parentRoute: typeof AuthenticatedCentrosDeCustoRouteRoute
    }
  }
}

interface AuthenticatedCentrosDeCustoRouteRouteChildren {
  AuthenticatedCentrosDeCustoRelatorioRoute: typeof AuthenticatedCentrosDeCustoRelatorioRoute
  AuthenticatedCentrosDeCustoIndexRoute: typeof AuthenticatedCentrosDeCustoIndexRoute
}

const AuthenticatedCentrosDeCustoRouteRouteChildren: AuthenticatedCentrosDeCustoRouteRouteChildren =
  {
    AuthenticatedCentrosDeCustoRelatorioRoute:
      AuthenticatedCentrosDeCustoRelatorioRoute,
    AuthenticatedCentrosDeCustoIndexRoute:
      AuthenticatedCentrosDeCustoIndexRoute,
  }

const AuthenticatedCentrosDeCustoRouteRouteWithChildren =
  AuthenticatedCentrosDeCustoRouteRoute._addFileChildren(
    AuthenticatedCentrosDeCustoRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCentrosDeCustoRouteRoute: typeof AuthenticatedCentrosDeCustoRouteRouteWithChildren
  AuthenticatedAprovacoesRoute: typeof AuthenticatedAprovacoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedOrcamentoRoute: typeof AuthenticatedOrcamentoRoute
  AuthenticatedProjecaoRoute: typeof AuthenticatedProjecaoRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedConfiguracoesAprovacoesRoute: typeof AuthenticatedConfiguracoesAprovacoesRoute
  AuthenticatedConfiguracoesNotificacoesRoute: typeof AuthenticatedConfiguracoesNotificacoesRoute
  AuthenticatedFinanceiroCalendarioRoute: typeof AuthenticatedFinanceiroCalendarioRoute
  AuthenticatedFinanceiroCartoesRoute: typeof AuthenticatedFinanceiroCartoesRoute
  AuthenticatedFinanceiroCategoriasRoute: typeof AuthenticatedFinanceiroCategoriasRoute
  AuthenticatedFinanceiroConciliacaoRoute: typeof AuthenticatedFinanceiroConciliacaoRoute
  AuthenticatedFinanceiroContasBancariasRoute: typeof AuthenticatedFinanceiroContasBancariasRoute
  AuthenticatedFinanceiroContasPagarRoute: typeof AuthenticatedFinanceiroContasPagarRoute
  AuthenticatedFinanceiroContasReceberRoute: typeof AuthenticatedFinanceiroContasReceberRoute
  AuthenticatedFinanceiroFluxoCaixaRoute: typeof AuthenticatedFinanceiroFluxoCaixaRoute
  AuthenticatedFinanceiroImportarRoute: typeof AuthenticatedFinanceiroImportarRoute
  AuthenticatedFinanceiroRegrasNomesRoute: typeof AuthenticatedFinanceiroRegrasNomesRoute
  AuthenticatedFinanceiroTransacoesRoute: typeof AuthenticatedFinanceiroTransacoesRoute
  AuthenticatedVendasClientesRoute: typeof AuthenticatedVendasClientesRoute
  AuthenticatedVendasPedidosRoute: typeof AuthenticatedVendasPedidosRoute
  AuthenticatedVendasProdutosRoute: typeof AuthenticatedVendasProdutosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCentrosDeCustoRouteRoute:
    AuthenticatedCentrosDeCustoRouteRouteWithChildren,
  AuthenticatedAprovacoesRoute: AuthenticatedAprovacoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedOrcamentoRoute: AuthenticatedOrcamentoRoute,
  AuthenticatedProjecaoRoute: AuthenticatedProjecaoRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedConfiguracoesAprovacoesRoute:
    AuthenticatedConfiguracoesAprovacoesRoute,
  AuthenticatedConfiguracoesNotificacoesRoute:
    AuthenticatedConfiguracoesNotificacoesRoute,
  AuthenticatedFinanceiroCalendarioRoute:
    AuthenticatedFinanceiroCalendarioRoute,
  AuthenticatedFinanceiroCartoesRoute: AuthenticatedFinanceiroCartoesRoute,
  AuthenticatedFinanceiroCategoriasRoute:
    AuthenticatedFinanceiroCategoriasRoute,
  AuthenticatedFinanceiroConciliacaoRoute:
    AuthenticatedFinanceiroConciliacaoRoute,
  AuthenticatedFinanceiroContasBancariasRoute:
    AuthenticatedFinanceiroContasBancariasRoute,
  AuthenticatedFinanceiroContasPagarRoute:
    AuthenticatedFinanceiroContasPagarRoute,
  AuthenticatedFinanceiroContasReceberRoute:
    AuthenticatedFinanceiroContasReceberRoute,
  AuthenticatedFinanceiroFluxoCaixaRoute:
    AuthenticatedFinanceiroFluxoCaixaRoute,
  AuthenticatedFinanceiroImportarRoute: AuthenticatedFinanceiroImportarRoute,
  AuthenticatedFinanceiroRegrasNomesRoute:
    AuthenticatedFinanceiroRegrasNomesRoute,
  AuthenticatedFinanceiroTransacoesRoute:
    AuthenticatedFinanceiroTransacoesRoute,
  AuthenticatedVendasClientesRoute: AuthenticatedVendasClientesRoute,
  AuthenticatedVendasPedidosRoute: AuthenticatedVendasPedidosRoute,
  AuthenticatedVendasProdutosRoute: AuthenticatedVendasProdutosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
